# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161016_1736'),
    ]

    operations = [
        migrations.RenameField('tag', 'value', 'slug'),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.SlugField(max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='value_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
