# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161019_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
