# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('book', 'title_orig', 'title_en'),
        migrations.RenameField('author', 'value', 'value_ru'),
        migrations.AddField(
            model_name='author',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='value',
            field=models.CharField(max_length=150, null=True, verbose_name='Author'),
        ),
        migrations.RenameField('author', 'wiki_url', 'wiki_url_ru'),
        migrations.AddField(
            model_name='author',
            name='wiki_url',
            field=models.TextField(blank=True, null=True, verbose_name='Wikipedia url'),
        ),
        migrations.RenameField('book', 'about', 'about_ru'),
        migrations.AddField(
            model_name='book',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description about'),
        ),
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Short description about'),
        ),
        migrations.RenameField('book', 'title', 'title_ru'),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.RenameField('book', 'wiki_url', 'wiki_url_ru'),
        migrations.AddField(
            model_name='book',
            name='wiki_url',
            field=models.TextField(blank=True, null=True, verbose_name='Wikipedia url'),
        ),
        migrations.AddField(
            model_name='genre',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Genre'),
        ),
        migrations.RenameField('genre', 'value', 'value_ru'),
        migrations.AddField(
            model_name='genre',
            name='value',
            field=models.CharField(max_length=150, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='wiki_url_en',
            field=models.TextField(blank=True, null=True, verbose_name='Wikipedia url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='wiki_url_en',
            field=models.TextField(blank=True, null=True, verbose_name='Wikipedia url'),
        ),
    ]
