# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161011_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='value_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='value_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Genre'),
        ),
    ]
