# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-31 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20161016_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('created',), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
