# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180201_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Is active?'),
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='book',
            name='down_url',
            field=models.TextField(blank=True, null=True, verbose_name='Download url'),
        ),
        migrations.AddField(
            model_name='book',
            name='down_url_en',
            field=models.TextField(blank=True, null=True, verbose_name='Download url'),
        ),
        migrations.AddField(
            model_name='book',
            name='down_url_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Download url'),
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='Where I found the book from?'),
        ),
    ]
