# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-14 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190414_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created',), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
