# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190415_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='countries',
            field=models.ManyToManyField(blank=True, to='travel.Country', verbose_name='Country'),
        ),
    ]
