# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20160319_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
