# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


def copy_fields(apps, schema_editor):
    Tag = apps.get_model('travel', 'Tag')
    for mm in Tag.objects.all():
        old_field = mm.value
        mm.value_en = old_field
        mm.value_ru = old_field
        mm.slug = old_field.lower().replace(" ", "_")
        mm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20161011_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=150, verbose_name='Tag url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='value_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.RunPython(copy_fields),
    ]
