# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20161015_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='example',
            field=models.TextField(blank=True, null=True, verbose_name='Url to example'),
        ),
    ]
