# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_country_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='example',
            field=models.ImageField(blank=True, null=True, upload_to=b'ball_examples/', verbose_name=b'Country ball'),
        ),
    ]
