# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20161015_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='country',
            name='example',
            field=models.ImageField(blank=True, null=True, upload_to=b'ball_examples/', verbose_name=b'Example'),
        ),
    ]
