# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20161016_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='psdfile',
            field=models.ImageField(blank=True, null=True, upload_to=b'ball_psd/', verbose_name=b'PSD file'),
        ),
    ]
