# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20180201_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='Link')),
                ('url_ru', models.CharField(max_length=1000, null=True, verbose_name='Link')),
                ('url_en', models.CharField(max_length=1000, null=True, verbose_name='Link')),
                ('description', models.CharField(max_length=256, verbose_name='Link description')),
                ('description_ru', models.CharField(max_length=256, null=True, verbose_name='Link description')),
                ('description_en', models.CharField(max_length=256, null=True, verbose_name='Link description')),
                ('isPoint', models.BooleanField(default=True, verbose_name='Is point?')),
                ('published', models.BooleanField(default=True, verbose_name='Is published?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Post')),
            ],
        ),
        migrations.AddField(
            model_name='postphoto',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Photo source'),
        ),
    ]
