# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20180204_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cities',
        ),
        migrations.AlterField(
            model_name='user',
            name='notifyEmail',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifyGlobal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifyNewposts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifyReplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
