# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_auto_20180219_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='metaTitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='metaTitle_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='metaTitle_ru',
        ),
    ]
