# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def copy_field(apps, schema_editor):
    Country = apps.get_model('travel', 'Country')
    for country in Country.objects.all():
        country.slug = country.title.replace(' ', '-').lower()
        country.save()

def copy_reversed(apps, schema_editor):
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20180818_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='value',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(default='', max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_field, reverse_code=copy_reversed),
    ]
