# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_auto_20190108_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sources'),
        ),
    ]
