# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_auto_20190415_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
