# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment ball work details'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.CharField(default='', max_length=256, verbose_name='Flag URL'),
            preserve_default=False,
        ),
    ]
