# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
