# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20181207_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='parent',
        ),
        migrations.AddField(
            model_name='list',
            name='template',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='List template'),
        ),
    ]
