# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190108_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='list',
            name='fields_en',
        ),
        migrations.RemoveField(
            model_name='list',
            name='fields_ru',
        ),
        migrations.AlterField(
            model_name='entry',
            name='item',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='item_en',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='item_ru',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
    ]
