# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20201011_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ImageSource',
            field=models.TextField(blank=True, null=True, verbose_name='Image source'),
        ),
    ]
